require('plugins')
require('lv-airline')
require('lv-utils')
require('lv-autocommands')
require('settings')
require('keymappings')
require('lv-comment')
require('lv-compe')
require('lv-telescope')
require('lv-nvimtree')
require('lv-startify')
require('lv-treesitter')
require('lv-autopairs')
require('lv-vsnip')

-- Which Key (Hope to replace with Lua plugin someday)
vim.cmd('source ~/.config/nvim/vimscript/lv-whichkey/init.vim')
vim.cmd('source ~/.config/nvim/vimscript/functions.vim')

-- LSP
require('lsp')
require('lspconfig')
require('lspconfig.intelephense')
require('lspconfig.angularls')
require('lspconfig.html')
require('lspconfig.jsonls')
require('lspconfig.cssls')
require('lspconfig.tsserver')
require('lspconfig.vimls')
require('lspconfig.sqlls')
require('lspconfig.omnisharp')
require('lspconfig.dartls')
