require("configs.treesitter")
require("configs.lualine")
require("configs.bufferline")
require("configs.nvim-tree")
require("configs.nvim-autoparts")
require("configs.telescope")
require("configs.startify")
require("configs.gitsigns")
require("configs.indent-blank-line")
require("configs.toggleterm")
require("configs.commentary")
require("configs.hardmode")
require("configs.laravel")
require("configs.fold")
require("configs.snippets")
require("configs.projectionist")

require("configs.flutter-tools")
require("configs.lsp.cmp")
require("configs.lsp.mason")
require("configs.lsp.lspsaga")
require("configs.lsp.lspconfig")
require("configs.lsp.null-ls")

require("configs.dap")
require("configs.dap.ui")
require("configs.dap.nvim-dap-virtual-text")
require("configs.dap._php")
require("configs.db-ui")
require("configs.test")
-- require('configs.which-key')
