#!/bin/zsh

# lista

alias l='ls -alh'

alias gpushall="git remote | xargs -L1 git push --all"
alias dds="sudo find . -name '*.DS_Store' -type f -delete"

# show/hide hidden files

alias files-show='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias files-hide='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'

# cleaners

alias cleanxcode='rm -frdv ~/Library/Developer/Xcode/DerivedData && sudo rm -frdv ~/Library/Caches/com.apple.dt.Xcode && rm -frdv ~/Library/Developer/CoreSimulator'
alias cleancode='rm -frdv ~/Library/Application\ Support/Code/User/workspaceStorage'
alias cleanmac='sudo rm -rfv ~/Library/Caches/ && sudo rm -rfv /Library/Caches/ && sudo rm -frdv /.Spotlight-V100'

alias move-all='rsync -rv --remove-source-files /Users/juan/Desktop/* /Volumes/jfv1_a/Desktop && rsync -rv --remove-source-files /Users/juan/Documents/* /Volumes/jfv1_a/Documents && rsync -rv --remove-source-files /Users/juan/Downloads/* /Volumes/jfv1_a/Downloads'
alias move-wsp='rsync -rv --remove-source-files /Users/juan/workspace/* /Volumes/jfv1_a/workspace'
alias move-wsp='rsync -rv --remove-source-files /Users/juan/workspace/* /Volumes/jfv1_a/workspace'

# mysql command

alias mys='sudo mysql.server start'
alias myp='sudo mysql.server stop'
alias myr='sudo mysql.server restart'

alias luamake=/Users/juan/.config/lang-servers/lua-language-server/3rd/luamake/luamake

# folders

alias o-httpd='code /usr/local/etc/httpd/'
alias o-php='code /usr/local/etc/php/'

# wakatime

alias waka-j="printf \"[settings]\napi_key = 4abc7490-a71a-4bb3-a5fb-50d2d8612453\nstatus_bar_enabled = true\" > ~/.wakatime.cfg"
alias waka-m="printf \"[settings]\napi_key = 6b754014-683e-43ad-9d9a-55b780792e6e\nstatus_bar_enabled = true\" > ~/.wakatime.cfg"

# php/laravel

alias phpi="pecl uninstall -r xdebug && pecl install xdebug && pecl uninstall -r imagick && pecl install imagick"
alias part="php artisan"
alias pasr="php artisan schedule:run"
alias pasl="php artisan schedule:list"
alias pide="php artisan ide-helper:generate"
alias pide-r="php artisan ide-helper:reset"
alias pide-m="php artisan ide-helper:models --nowrite"

alias ptf="clear && php artisan test --filter"
alias ptp="clear && php artisan test --parallel"
alias pta="clear && php artisan test"

alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'
