#!/bin/zsh

## Env variables
export E=/Volumes/jfv2
export EHOME=$E$HOME
export DC=/Volumes/jfv3_c/

## Symbolic links

# Create a symlink to External Drive to preserve internal drive.
# ln -s $EHOME/Library/Containers/com.docker.docker /Users/juan/Library/Containers

# Useful Functions
source "$ZSHDIR/functions"

zsh_add_file "alias"
# zsh_add_file "prompt"

# Plugins
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"

[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export PATH="/opt/local/bin:$PATH"
export PATH="/opt/local/sbin:$PATH"
export PATH="/usr/local/sbin:$PATH"

# mysql
export PATH="/usr/local/mysql/bin:$PATH"
# android
export ANDROID_HOME="$DC/Library/Android/sdk"
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH"
# flutter
export PATH="$DC/Library/flutter/bin:$PATH"
# Laravel
export PATH="$HOME/.composer/vendor/bin:$PATH"
# maven
export PATH="$HOME/workspace/_.libs/apache-maven-3.5.0/bin:$PATH"

# The original version is saved in .bash_profile.pysave
export PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:$PATH"
export PATH="/Users/juan/Documents/sonar-scanner-4.7.0.2747-macosx/bin:$PATH"
export PATH="$HOME/.pub-cache/bin:$PATH"



